# Clonal Selection Algorithm (CSA)

This notebook implements a simple and explainable version of the Clonal Selection Algorithm (CSA) in Python.

CSA is inspired by the natural immune system and is used for optimization problems. It works by generating a population of candidate solutions (antibodies), selecting the best ones, cloning them, introducing mutations, and selecting the best individuals for the next generation.

In [1]:
import numpy as np


# Objective function: Sphere function (minimize sum of squares)
def objective(x):
    return np.sum(x**2)

## Step 1: Initialize Population
Generate a random population of candidate solutions (antibodies).

In [2]:
def initialize_population(pop_size, dim, lower, upper):
    return np.random.uniform(lower, upper, (pop_size, dim))


pop_size = 10
dim = 2
lower, upper = -5, 5
population = initialize_population(pop_size, dim, lower, upper)
population

array([[-3.06640559, -3.84223576],
       [ 4.97400973,  1.66912189],
       [-4.37640681, -1.23845097],
       [-4.62306102, -1.20668399],
       [ 2.2474182 , -1.09200705],
       [ 4.63388498,  2.38587744],
       [ 0.44679845,  4.89190411],
       [ 2.81761612, -3.74451107],
       [ 2.35565474,  3.20186017],
       [-0.21581706, -0.39148857]])

## Step 2: Evaluate Fitness
Calculate the fitness (objective value) for each antibody.

In [3]:
fitness = np.array([objective(ind) for ind in population])
fitness

array([24.16561885, 27.52674072, 20.68669739, 22.82877948,  6.24336795,
       27.16530118, 24.13035471, 21.96032371, 15.80101781,  0.1998403 ])

## Step 3: Select Best Antibodies
Select the top N antibodies with the best (lowest) fitness.

In [4]:
num_selected = 4
selected_indices = np.argsort(fitness)[:num_selected]
selected = population[selected_indices]
selected

array([[-0.21581706, -0.39148857],
       [ 2.2474182 , -1.09200705],
       [ 2.35565474,  3.20186017],
       [-4.37640681, -1.23845097]])

## Step 4: Clone and Mutate
Clone the selected antibodies and introduce random mutations.

In [5]:
def clone_and_mutate(selected, clones_per_antibody, mutation_rate=0.2):
    clones = []
    for antibody in selected:
        for _ in range(clones_per_antibody):
            clone = antibody.copy()
            mutation = np.random.normal(0, mutation_rate, size=antibody.shape)
            clone += mutation
            clones.append(clone)
    return np.array(clones)


clones_per_antibody = 3
clones = clone_and_mutate(selected, clones_per_antibody)
clones

array([[-0.2384534 , -0.30347042],
       [ 0.02840708, -0.32580464],
       [-0.39138556, -0.48183309],
       [ 2.35822518, -1.13462716],
       [ 2.08422849, -1.03506043],
       [ 2.37842626, -1.19856559],
       [ 2.35744734,  3.12237059],
       [ 2.23541081,  3.03141123],
       [ 2.4077821 ,  3.14472304],
       [-4.14008517, -0.99931271],
       [-4.15518628, -1.31837304],
       [-4.53390488, -1.4879951 ]])

## Step 5: Select Next Generation
Combine original population and clones, select the best individuals for the next generation.

In [6]:
combined = np.vstack((population, clones))
combined_fitness = np.array([objective(ind) for ind in combined])
next_gen_indices = np.argsort(combined_fitness)[:pop_size]
population = combined[next_gen_indices]
population

array([[ 0.02840708, -0.32580464],
       [-0.2384534 , -0.30347042],
       [-0.21581706, -0.39148857],
       [-0.39138556, -0.48183309],
       [ 2.08422849, -1.03506043],
       [ 2.2474182 , -1.09200705],
       [ 2.35822518, -1.13462716],
       [ 2.37842626, -1.19856559],
       [ 2.23541081,  3.03141123],
       [ 2.35744734,  3.12237059]])

## Step 6: Repeat
Repeat the process for a number of generations.

In [7]:
generations = 10
for gen in range(generations):
    fitness = np.array([objective(ind) for ind in population])
    selected_indices = np.argsort(fitness)[:num_selected]
    selected = population[selected_indices]
    clones = clone_and_mutate(selected, clones_per_antibody)
    combined = np.vstack((population, clones))
    combined_fitness = np.array([objective(ind) for ind in combined])
    next_gen_indices = np.argsort(combined_fitness)[:pop_size]
    population = combined[next_gen_indices]
    print(
        f"Generation {gen + 1}, Best Fitness: {combined_fitness[next_gen_indices[0]]:.4f}"
    )

Generation 1, Best Fitness: 0.0211
Generation 2, Best Fitness: 0.0021
Generation 3, Best Fitness: 0.0009
Generation 4, Best Fitness: 0.0009
Generation 5, Best Fitness: 0.0009
Generation 6, Best Fitness: 0.0006
Generation 7, Best Fitness: 0.0006
Generation 8, Best Fitness: 0.0006
Generation 9, Best Fitness: 0.0004
Generation 10, Best Fitness: 0.0004


## Conclusion
This notebook demonstrates a simple and explainable implementation of the Clonal Selection Algorithm. You can explain each step to your instructor, showing how the population evolves and improves over generations.